server:
  port: ${USER_API_PORT}

spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver

  boot:
    admin:
      client:
        url: "http://spring-boot-admin:8060"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
