apiVersion: 1

datasources:
  -  access: 'proxy'
     editable: true
     is_default: true
     name: 'prometheus'
     org_id: 1
     type: 'prometheus'
     url: 'http://prometheus:9090'
     uid: prometheus_ds
     version: 1
  -  name: Loki
     type: loki
     access: proxy
     orgId: 1
     url: http://loki:3100
     basicAuth: false
     isDefault: true
     version: 1
     editable: false