version: "3.9"
services:
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_INTERNAL_PORT}

  pgadmin:
    restart: always
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_USER}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '*:${POSTGRES_INTERNAL_PORT}:${POSTGRES_DB}:${POSTGRES_USER}:${POSTGRES_PASS}' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - ${PGADMIN_PORT}:80
    profiles:
      - local

  rabbitmq:
    restart: always
    image: rabbitmq:3.9.11
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMIN_PORT}:15672

  user-api:
    restart: always
    image: abogomazov/user-api:latest
    ports:
      - ${USER_API_PORT}:${USER_API_PORT}
    environment:
      - SERVER_PORT=${USER_API_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_INTERNAL_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - rabbitmq

  spring-boot-admin:
    restart: always
    image: abogomazov/spring-boot-admin:latest
    ports:
      - 18060:8060

  portainer:
    restart: always
    image: portainer/portainer:1.25.0
    ports:
      - ${PORTAINER_PORT}:9000
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    profiles:
      - local

  prometheus:
    image: prom/prometheus
    ports:
      - ${PROMETHEUS_PORT}:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - ${GRAFANA_PORT}:3000
    volumes:
      - ./dashboards.yaml:/etc/grafana/provisioning/dashboards/all.yaml
      - ./datasources.yaml:/etc/grafana/provisioning/datasources/all.yaml
      - ./spring-boot-dashboard.json:/var/lib/grafana/dashboards/spring-boot-dashboard.json

volumes:
  portainer_data:
  postgres:
  pgadmin:
  prometheus:
  grafana:
