version: "3.9"
services:
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=abogomazov
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=user-api
    volumes:
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    restart: always
    image: dpage/pgadmin4:8.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=abogomazov.dev@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '*:5432:user-api:abogomazov:pass' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - ${PGADMIN_PORT}:80
    profiles:
      - local

  rabbitmq:
    restart: always
    image: rabbitmq:3.9.11
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMIN_PORT}:15672

  user-api:
    restart: always
    image: abogomazov/user-api:latest
    ports:
      - ${USER_API_PORT}:${USER_API_PORT}
    environment:
      - SERVER_PORT=${USER_API_PORT}
    depends_on:
      - rabbitmq

  portainer:
    restart: always
    image: portainer/portainer:1.25.0
    ports:
      - ${PORTAINER_PORT}:9000
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    profiles:
      - local

volumes:
  portainer_data:
  postgres:
  pgadmin: