server:
  port: ${USER_API_PORT}

spring:
  application:
    name: user-api

# PERSISTENCE: Data migration and datasource config
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    driver-class-name: org.postgresql.Driver

# OBSERVABILITY: Spring boot admin server, logging pattern and actuator endpoints
  boot:
    admin:
      client:
        url: "http://spring-boot-admin:${SPRING_BOOT_ADMIN_INTERNAL_PORT}"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
